---

name: NX1 Deploy to greentea-dev1-us-west-2
run-name: Deploy to greentea-dev1-us-west-2 (us-west-2/481313360369) by @${{ github.actor }}

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: NX1 Deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Optional step: Detect app and construct Dockerfile using Nixpacks
      - name: NX1 Build with Nixpacks
        uses: nx1-io/app-copilot-action@main
        with:
          operation: 'build-nixpacks'

      - name: NX1 Prepare Deployment
        uses: nx1-io/dev-app-copilot-action@feature/app-addons
        with:
          operation: 'prepare'
          app_id: 9ae416d2-9b5c-44cf-a901-8306eea8adb5
          api_url: 'https://dev-app.citadel.run/api'
          api_token: ${{ secrets.NX1_API_TOKEN }}
          env_id: 381c52c0-4306-472b-9131-fd562d5f0ac1

      - name: NX1 Assume Role
        uses: nx1-io/app-copilot-action@main
        with:
          operation: 'assume-role'

      - name: NX1 Deploy Service - web
        uses: nx1-io/app-copilot-action@main
        with:
          operation: 'deploy'
          service: 'web'

# rev:1