name: Citadel Deploy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: NX1 Action [IN DEVELOPMENT]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: NX1 Prepare Deployment
        uses: citadel-runcloud/dev-composite-action@main
        with:
          operation: 'prepare'
          app_id: 9acfc1ad-79cb-4338-b6f8-91411082b51c
          api_url: 'https://dev-app.citadel.run/api'
          api_token: uat6a5WQtcbgPxMC9b8t7ltRzllk81Sm63VIepTa6aa73cd2
          env_id: 4c902cae-c43f-4be0-83b6-0df7173f8184

      - name: NX1 Build with Nixpacks
        uses: citadel-runcloud/dev-composite-action@main
        with:
          operation: 'build-nixpacks'

      - name: NX1 Assume Role
        uses: citadel-runcloud/dev-composite-action@main
        with:
          operation: 'assume-role'

      - name: NX1 Deploy Service
        uses: citadel-runcloud/dev-composite-action@main
        with:
          operation: 'deploy'
          service: 'web'

      - name: NX1 Migrate Service
        uses: citadel-runcloud/dev-composite-action@main
        with:
          operation: 'run'
          service: 'web'
          command: 'php artisan migrate'